tasks:
  - name: Frontend
    before: |
      cd frontend
      npm ci
    command: |
      cd frontend
      npm start

ports:
  - name: Frontend
    port: 3000
    description: React PWA app
    visibility: public
    onOpen: open-browser
